// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: memory/v1/memory.proto

package memorypb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Memory is the core memory record.
type Memory struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content    string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Summary    string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Project    string                 `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Type       string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Visibility string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Source     string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	SourceFile string                 `protobuf:"bytes,8,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	ParentId   string                 `protobuf:"bytes,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChunkIndex int32                  `protobuf:"varint,10,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	CreatedAt  string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TokenCount int32                  `protobuf:"varint,13,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	Tags       []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// Taxonomy: who said/wrote this (j33p, gilfoyle, agent, system)
	Speaker string `protobuf:"bytes,15,opt,name=speaker,proto3" json:"speaker,omitempty"`
	// Taxonomy: top-level domain (work, home, family, homelab, project, meta)
	Area string `protobuf:"bytes,16,opt,name=area,proto3" json:"area,omitempty"`
	// Taxonomy: sub-domain, free-form (power-platform, proxmox, magi, etc.)
	SubArea       string `protobuf:"bytes,17,opt,name=sub_area,json=subArea,proto3" json:"sub_area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memory) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Memory) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Memory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Memory) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Memory) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Memory) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *Memory) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Memory) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Memory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Memory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Memory) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *Memory) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Memory) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *Memory) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Memory) GetSubArea() string {
	if x != nil {
		return x.SubArea
	}
	return ""
}

// MemoryResult wraps a Memory with relevance scores from hybrid search.
type MemoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *Memory                `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	RrfScore      float64                `protobuf:"fixed64,2,opt,name=rrf_score,json=rrfScore,proto3" json:"rrf_score,omitempty"`
	VecRank       int32                  `protobuf:"varint,3,opt,name=vec_rank,json=vecRank,proto3" json:"vec_rank,omitempty"`
	Bm25Rank      int32                  `protobuf:"varint,4,opt,name=bm25_rank,json=bm25Rank,proto3" json:"bm25_rank,omitempty"`
	Distance      float64                `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	RecencyWeight float64                `protobuf:"fixed64,7,opt,name=recency_weight,json=recencyWeight,proto3" json:"recency_weight,omitempty"`
	WeightedScore float64                `protobuf:"fixed64,8,opt,name=weighted_score,json=weightedScore,proto3" json:"weighted_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResult) Reset() {
	*x = MemoryResult{}
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResult) ProtoMessage() {}

func (x *MemoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResult.ProtoReflect.Descriptor instead.
func (*MemoryResult) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryResult) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MemoryResult) GetRrfScore() float64 {
	if x != nil {
		return x.RrfScore
	}
	return 0
}

func (x *MemoryResult) GetVecRank() int32 {
	if x != nil {
		return x.VecRank
	}
	return 0
}

func (x *MemoryResult) GetBm25Rank() int32 {
	if x != nil {
		return x.Bm25Rank
	}
	return 0
}

func (x *MemoryResult) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *MemoryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResult) GetRecencyWeight() float64 {
	if x != nil {
		return x.RecencyWeight
	}
	return 0
}

func (x *MemoryResult) GetWeightedScore() float64 {
	if x != nil {
		return x.WeightedScore
	}
	return 0
}

// Remember
type RememberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Speaker       string                 `protobuf:"bytes,8,opt,name=speaker,proto3" json:"speaker,omitempty"`                 // j33p, gilfoyle, agent, system
	Area          string                 `protobuf:"bytes,9,opt,name=area,proto3" json:"area,omitempty"`                       // work, home, family, homelab, project, meta
	SubArea       string                 `protobuf:"bytes,10,opt,name=sub_area,json=subArea,proto3" json:"sub_area,omitempty"` // free-form sub-domain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberRequest) Reset() {
	*x = RememberRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberRequest) ProtoMessage() {}

func (x *RememberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberRequest.ProtoReflect.Descriptor instead.
func (*RememberRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *RememberRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RememberRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RememberRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RememberRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RememberRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *RememberRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RememberRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RememberRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *RememberRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *RememberRequest) GetSubArea() string {
	if x != nil {
		return x.SubArea
	}
	return ""
}

type RememberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	TagWarning    string                 `protobuf:"bytes,3,opt,name=tag_warning,json=tagWarning,proto3" json:"tag_warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberResponse) Reset() {
	*x = RememberResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberResponse) ProtoMessage() {}

func (x *RememberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberResponse.ProtoReflect.Descriptor instead.
func (*RememberResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RememberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RememberResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RememberResponse) GetTagWarning() string {
	if x != nil {
		return x.TagWarning
	}
	return ""
}

// Recall
type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Projects      []string               `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TopK          int32                  `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MinRelevance  float64                `protobuf:"fixed64,7,opt,name=min_relevance,json=minRelevance,proto3" json:"min_relevance,omitempty"`
	RecencyDecay  float64                `protobuf:"fixed64,8,opt,name=recency_decay,json=recencyDecay,proto3" json:"recency_decay,omitempty"`
	Speaker       string                 `protobuf:"bytes,9,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Area          string                 `protobuf:"bytes,10,opt,name=area,proto3" json:"area,omitempty"`
	SubArea       string                 `protobuf:"bytes,11,opt,name=sub_area,json=subArea,proto3" json:"sub_area,omitempty"`
	AfterTime     string                 `protobuf:"bytes,12,opt,name=after_time,json=afterTime,proto3" json:"after_time,omitempty"`
	BeforeTime    string                 `protobuf:"bytes,13,opt,name=before_time,json=beforeTime,proto3" json:"before_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RecallRequest) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *RecallRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecallRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecallRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RecallRequest) GetMinRelevance() float64 {
	if x != nil {
		return x.MinRelevance
	}
	return 0
}

func (x *RecallRequest) GetRecencyDecay() float64 {
	if x != nil {
		return x.RecencyDecay
	}
	return 0
}

func (x *RecallRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *RecallRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *RecallRequest) GetSubArea() string {
	if x != nil {
		return x.SubArea
	}
	return ""
}

func (x *RecallRequest) GetAfterTime() string {
	if x != nil {
		return x.AfterTime
	}
	return ""
}

func (x *RecallRequest) GetBeforeTime() string {
	if x != nil {
		return x.BeforeTime
	}
	return ""
}

type RecallResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*MemoryResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Rewritten      bool                   `protobuf:"varint,2,opt,name=rewritten,proto3" json:"rewritten,omitempty"`
	RewrittenQuery string                 `protobuf:"bytes,3,opt,name=rewritten_query,json=rewrittenQuery,proto3" json:"rewritten_query,omitempty"`
	Attempts       int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *RecallResponse) GetResults() []*MemoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RecallResponse) GetRewritten() bool {
	if x != nil {
		return x.Rewritten
	}
	return false
}

func (x *RecallResponse) GetRewrittenQuery() string {
	if x != nil {
		return x.RewrittenQuery
	}
	return ""
}

func (x *RecallResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

// Forget
type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *ForgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ForgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetResponse) Reset() {
	*x = ForgetResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetResponse) ProtoMessage() {}

func (x *ForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetResponse.ProtoReflect.Descriptor instead.
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *ForgetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForgetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// List
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"` // comma-separated for HTTP GET query param compat
	Speaker       string                 `protobuf:"bytes,6,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Area          string                 `protobuf:"bytes,7,opt,name=area,proto3" json:"area,omitempty"`
	SubArea       string                 `protobuf:"bytes,8,opt,name=sub_area,json=subArea,proto3" json:"sub_area,omitempty"`
	AfterTime     string                 `protobuf:"bytes,9,opt,name=after_time,json=afterTime,proto3" json:"after_time,omitempty"`
	BeforeTime    string                 `protobuf:"bytes,10,opt,name=before_time,json=beforeTime,proto3" json:"before_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *ListRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *ListRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ListRequest) GetSubArea() string {
	if x != nil {
		return x.SubArea
	}
	return ""
}

func (x *ListRequest) GetAfterTime() string {
	if x != nil {
		return x.AfterTime
	}
	return ""
}

func (x *ListRequest) GetBeforeTime() string {
	if x != nil {
		return x.BeforeTime
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*Memory              `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetMemories() []*Memory {
	if x != nil {
		return x.Memories
	}
	return nil
}

// Health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// CreateConversation
type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	SessionKey    string                 `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	TurnCount     int32                  `protobuf:"varint,6,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	Topics        []string               `protobuf:"bytes,7,rep,name=topics,proto3" json:"topics,omitempty"`
	Decisions     []string               `protobuf:"bytes,8,rep,name=decisions,proto3" json:"decisions,omitempty"`
	ActionItems   []string               `protobuf:"bytes,9,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *CreateConversationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CreateConversationRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateConversationRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *CreateConversationRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CreateConversationRequest) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *CreateConversationRequest) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *CreateConversationRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CreateConversationRequest) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *CreateConversationRequest) GetActionItems() []string {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	TagWarning    string                 `protobuf:"bytes,3,opt,name=tag_warning,json=tagWarning,proto3" json:"tag_warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *CreateConversationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateConversationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateConversationResponse) GetTagWarning() string {
	if x != nil {
		return x.TagWarning
	}
	return ""
}

// SearchConversations
type SearchConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	MinRelevance  float64                `protobuf:"fixed64,4,opt,name=min_relevance,json=minRelevance,proto3" json:"min_relevance,omitempty"`
	RecencyDecay  float64                `protobuf:"fixed64,5,opt,name=recency_decay,json=recencyDecay,proto3" json:"recency_decay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConversationsRequest) Reset() {
	*x = SearchConversationsRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationsRequest) ProtoMessage() {}

func (x *SearchConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationsRequest.ProtoReflect.Descriptor instead.
func (*SearchConversationsRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{14}
}

func (x *SearchConversationsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchConversationsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SearchConversationsRequest) GetMinRelevance() float64 {
	if x != nil {
		return x.MinRelevance
	}
	return 0
}

func (x *SearchConversationsRequest) GetRecencyDecay() float64 {
	if x != nil {
		return x.RecencyDecay
	}
	return 0
}

type SearchConversationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*MemoryResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Rewritten      bool                   `protobuf:"varint,2,opt,name=rewritten,proto3" json:"rewritten,omitempty"`
	RewrittenQuery string                 `protobuf:"bytes,3,opt,name=rewritten_query,json=rewrittenQuery,proto3" json:"rewritten_query,omitempty"`
	Attempts       int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchConversationsResponse) Reset() {
	*x = SearchConversationsResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationsResponse) ProtoMessage() {}

func (x *SearchConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationsResponse.ProtoReflect.Descriptor instead.
func (*SearchConversationsResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{15}
}

func (x *SearchConversationsResponse) GetResults() []*MemoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchConversationsResponse) GetRewritten() bool {
	if x != nil {
		return x.Rewritten
	}
	return false
}

func (x *SearchConversationsResponse) GetRewrittenQuery() string {
	if x != nil {
		return x.RewrittenQuery
	}
	return ""
}

func (x *SearchConversationsResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

var File_memory_v1_memory_proto protoreflect.FileDescriptor

const file_memory_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x16memory/v1/memory.proto\x12\tmemory.v1\x1a\x1cgoogle/api/annotations.proto\"\xcd\x03\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\aproject\x18\x04 \x01(\tR\aproject\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_file\x18\b \x01(\tR\n" +
	"sourceFile\x12\x1b\n" +
	"\tparent_id\x18\t \x01(\tR\bparentId\x12\x1f\n" +
	"\vchunk_index\x18\n" +
	" \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vtoken_count\x18\r \x01(\x05R\n" +
	"tokenCount\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x18\n" +
	"\aspeaker\x18\x0f \x01(\tR\aspeaker\x12\x12\n" +
	"\x04area\x18\x10 \x01(\tR\x04area\x12\x19\n" +
	"\bsub_area\x18\x11 \x01(\tR\asubArea\"\x8e\x02\n" +
	"\fMemoryResult\x12)\n" +
	"\x06memory\x18\x01 \x01(\v2\x11.memory.v1.MemoryR\x06memory\x12\x1b\n" +
	"\trrf_score\x18\x02 \x01(\x01R\brrfScore\x12\x19\n" +
	"\bvec_rank\x18\x03 \x01(\x05R\avecRank\x12\x1b\n" +
	"\tbm25_rank\x18\x04 \x01(\x05R\bbm25Rank\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x01R\bdistance\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12%\n" +
	"\x0erecency_weight\x18\a \x01(\x01R\rrecencyWeight\x12%\n" +
	"\x0eweighted_score\x18\b \x01(\x01R\rweightedScore\"\x88\x02\n" +
	"\x0fRememberRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x18\n" +
	"\aspeaker\x18\b \x01(\tR\aspeaker\x12\x12\n" +
	"\x04area\x18\t \x01(\tR\x04area\x12\x19\n" +
	"\bsub_area\x18\n" +
	" \x01(\tR\asubArea\"S\n" +
	"\x10RememberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1f\n" +
	"\vtag_warning\x18\x03 \x01(\tR\n" +
	"tagWarning\"\xab\x02\n" +
	"\rRecallRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1a\n" +
	"\bprojects\x18\x03 \x03(\tR\bprojects\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x13\n" +
	"\x05top_k\x18\x06 \x01(\x05R\x04topK\x12#\n" +
	"\rmin_relevance\x18\a \x01(\x01R\fminRelevance\x12#\n" +
	"\rrecency_decay\x18\b \x01(\x01R\frecencyDecay\x12\x18\n" +
	"\aspeaker\x18\t \x01(\tR\aspeaker\x12\x12\n" +
	"\x04area\x18\n" +
	" \x01(\tR\x04area\x12\x19\n" +
	"\bsub_area\x18\v \x01(\tR\asubArea\"\xa6\x01\n" +
	"\x0eRecallResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.memory.v1.MemoryResultR\aresults\x12\x1c\n" +
	"\trewritten\x18\x02 \x01(\bR\trewritten\x12'\n" +
	"\x0frewritten_query\x18\x03 \x01(\tR\x0erewrittenQuery\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\"\x1f\n" +
	"\rForgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x0eForgetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\xc6\x01\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x12\x18\n" +
	"\aspeaker\x18\x06 \x01(\tR\aspeaker\x12\x12\n" +
	"\x04area\x18\a \x01(\tR\x04area\x12\x19\n" +
	"\bsub_area\x18\b \x01(\tR\asubArea\"=\n" +
	"\fListResponse\x12-\n" +
	"\bmemories\x18\x01 \x03(\v2\x11.memory.v1.MemoryR\bmemories\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xa2\x02\n" +
	"\x19CreateConversationRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1f\n" +
	"\vsession_key\x18\x03 \x01(\tR\n" +
	"sessionKey\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\x12\x1d\n" +
	"\n" +
	"turn_count\x18\x06 \x01(\x05R\tturnCount\x12\x16\n" +
	"\x06topics\x18\a \x03(\tR\x06topics\x12\x1c\n" +
	"\tdecisions\x18\b \x03(\tR\tdecisions\x12!\n" +
	"\faction_items\x18\t \x03(\tR\vactionItems\"]\n" +
	"\x1aCreateConversationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1f\n" +
	"\vtag_warning\x18\x03 \x01(\tR\n" +
	"tagWarning\"\xac\x01\n" +
	"\x1aSearchConversationsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12#\n" +
	"\rmin_relevance\x18\x04 \x01(\x01R\fminRelevance\x12#\n" +
	"\rrecency_decay\x18\x05 \x01(\x01R\frecencyDecay\"\xb3\x01\n" +
	"\x1bSearchConversationsResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.memory.v1.MemoryResultR\aresults\x12\x1c\n" +
	"\trewritten\x18\x02 \x01(\bR\trewritten\x12'\n" +
	"\x0frewritten_query\x18\x03 \x01(\tR\x0erewrittenQuery\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts2\xb7\x05\n" +
	"\rMemoryService\x12Y\n" +
	"\bRemember\x12\x1a.memory.v1.RememberRequest\x1a\x1b.memory.v1.RememberResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/remember\x12Q\n" +
	"\x06Recall\x12\x18.memory.v1.RecallRequest\x1a\x19.memory.v1.RecallResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/recall\x12U\n" +
	"\x06Forget\x12\x18.memory.v1.ForgetRequest\x1a\x19.memory.v1.ForgetResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/memories/{id}\x12J\n" +
	"\x04List\x12\x16.memory.v1.ListRequest\x1a\x17.memory.v1.ListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/memories\x12N\n" +
	"\x06Health\x12\x18.memory.v1.HealthRequest\x1a\x19.memory.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12|\n" +
	"\x12CreateConversation\x12$.memory.v1.CreateConversationRequest\x1a%.memory.v1.CreateConversationResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/conversations\x12\x86\x01\n" +
	"\x13SearchConversations\x12%.memory.v1.SearchConversationsRequest\x1a&.memory.v1.SearchConversationsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/conversations/searchB;Z9github.com/j33pguy/magi/proto/memory/v1;memorypbb\x06proto3"

var (
	file_memory_v1_memory_proto_rawDescOnce sync.Once
	file_memory_v1_memory_proto_rawDescData []byte
)

func file_memory_v1_memory_proto_rawDescGZIP() []byte {
	file_memory_v1_memory_proto_rawDescOnce.Do(func() {
		file_memory_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)))
	})
	return file_memory_v1_memory_proto_rawDescData
}

var file_memory_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_memory_v1_memory_proto_goTypes = []any{
	(*Memory)(nil),                      // 0: memory.v1.Memory
	(*MemoryResult)(nil),                // 1: memory.v1.MemoryResult
	(*RememberRequest)(nil),             // 2: memory.v1.RememberRequest
	(*RememberResponse)(nil),            // 3: memory.v1.RememberResponse
	(*RecallRequest)(nil),               // 4: memory.v1.RecallRequest
	(*RecallResponse)(nil),              // 5: memory.v1.RecallResponse
	(*ForgetRequest)(nil),               // 6: memory.v1.ForgetRequest
	(*ForgetResponse)(nil),              // 7: memory.v1.ForgetResponse
	(*ListRequest)(nil),                 // 8: memory.v1.ListRequest
	(*ListResponse)(nil),                // 9: memory.v1.ListResponse
	(*HealthRequest)(nil),               // 10: memory.v1.HealthRequest
	(*HealthResponse)(nil),              // 11: memory.v1.HealthResponse
	(*CreateConversationRequest)(nil),   // 12: memory.v1.CreateConversationRequest
	(*CreateConversationResponse)(nil),  // 13: memory.v1.CreateConversationResponse
	(*SearchConversationsRequest)(nil),  // 14: memory.v1.SearchConversationsRequest
	(*SearchConversationsResponse)(nil), // 15: memory.v1.SearchConversationsResponse
}
var file_memory_v1_memory_proto_depIdxs = []int32{
	0,  // 0: memory.v1.MemoryResult.memory:type_name -> memory.v1.Memory
	1,  // 1: memory.v1.RecallResponse.results:type_name -> memory.v1.MemoryResult
	0,  // 2: memory.v1.ListResponse.memories:type_name -> memory.v1.Memory
	1,  // 3: memory.v1.SearchConversationsResponse.results:type_name -> memory.v1.MemoryResult
	2,  // 4: memory.v1.MemoryService.Remember:input_type -> memory.v1.RememberRequest
	4,  // 5: memory.v1.MemoryService.Recall:input_type -> memory.v1.RecallRequest
	6,  // 6: memory.v1.MemoryService.Forget:input_type -> memory.v1.ForgetRequest
	8,  // 7: memory.v1.MemoryService.List:input_type -> memory.v1.ListRequest
	10, // 8: memory.v1.MemoryService.Health:input_type -> memory.v1.HealthRequest
	12, // 9: memory.v1.MemoryService.CreateConversation:input_type -> memory.v1.CreateConversationRequest
	14, // 10: memory.v1.MemoryService.SearchConversations:input_type -> memory.v1.SearchConversationsRequest
	3,  // 11: memory.v1.MemoryService.Remember:output_type -> memory.v1.RememberResponse
	5,  // 12: memory.v1.MemoryService.Recall:output_type -> memory.v1.RecallResponse
	7,  // 13: memory.v1.MemoryService.Forget:output_type -> memory.v1.ForgetResponse
	9,  // 14: memory.v1.MemoryService.List:output_type -> memory.v1.ListResponse
	11, // 15: memory.v1.MemoryService.Health:output_type -> memory.v1.HealthResponse
	13, // 16: memory.v1.MemoryService.CreateConversation:output_type -> memory.v1.CreateConversationResponse
	15, // 17: memory.v1.MemoryService.SearchConversations:output_type -> memory.v1.SearchConversationsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_memory_v1_memory_proto_init() }
func file_memory_v1_memory_proto_init() {
	if File_memory_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_v1_memory_proto_goTypes,
		DependencyIndexes: file_memory_v1_memory_proto_depIdxs,
		MessageInfos:      file_memory_v1_memory_proto_msgTypes,
	}.Build()
	File_memory_v1_memory_proto = out.File
	file_memory_v1_memory_proto_goTypes = nil
	file_memory_v1_memory_proto_depIdxs = nil
}
